# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tilecachecreator.ui'
#
# Created: Tue Apr 29 13:11:29 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TileCacheCreator(object):
    def setupUi(self, TileCacheCreator):
        TileCacheCreator.setObjectName(_fromUtf8("TileCacheCreator"))
        TileCacheCreator.resize(671, 753)
        self.verticalLayoutWidget = QtGui.QWidget(TileCacheCreator)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 655, 734))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lhCacheName = QtGui.QHBoxLayout()
        self.lhCacheName.setObjectName(_fromUtf8("lhCacheName"))
        self.lblCacheName = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblCacheName.setObjectName(_fromUtf8("lblCacheName"))
        self.lhCacheName.addWidget(self.lblCacheName)
        self.leTileCacheConfig = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.leTileCacheConfig.setToolTip(_fromUtf8(""))
        self.leTileCacheConfig.setObjectName(_fromUtf8("leTileCacheConfig"))
        self.lhCacheName.addWidget(self.leTileCacheConfig)
        self.tbConfigFile = QtGui.QToolButton(self.verticalLayoutWidget)
        self.tbConfigFile.setObjectName(_fromUtf8("tbConfigFile"))
        self.lhCacheName.addWidget(self.tbConfigFile)
        self.verticalLayout.addLayout(self.lhCacheName)
        self.line_3 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.gbTileCacheSettings = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.gbTileCacheSettings.setObjectName(_fromUtf8("gbTileCacheSettings"))
        self.gridLayout = QtGui.QGridLayout(self.gbTileCacheSettings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.gbTileCacheSettings)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.leSourceName = QtGui.QLineEdit(self.gbTileCacheSettings)
        self.leSourceName.setObjectName(_fromUtf8("leSourceName"))
        self.gridLayout.addWidget(self.leSourceName, 2, 1, 1, 1)
        self.btnUpdate = QtGui.QToolButton(self.gbTileCacheSettings)
        self.btnUpdate.setMinimumSize(QtCore.QSize(0, 30))
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.gridLayout.addWidget(self.btnUpdate, 22, 0, 1, 1)
        self.lblMinZoom = QtGui.QLabel(self.gbTileCacheSettings)
        self.lblMinZoom.setObjectName(_fromUtf8("lblMinZoom"))
        self.gridLayout.addWidget(self.lblMinZoom, 10, 0, 1, 1)
        self.spMinZoom = QtGui.QSpinBox(self.gbTileCacheSettings)
        self.spMinZoom.setMaximum(20)
        self.spMinZoom.setObjectName(_fromUtf8("spMinZoom"))
        self.gridLayout.addWidget(self.spMinZoom, 10, 1, 1, 1)
        self.lblURL = QtGui.QLabel(self.gbTileCacheSettings)
        self.lblURL.setObjectName(_fromUtf8("lblURL"))
        self.gridLayout.addWidget(self.lblURL, 4, 0, 1, 1)
        self.lblLayer = QtGui.QLabel(self.gbTileCacheSettings)
        self.lblLayer.setObjectName(_fromUtf8("lblLayer"))
        self.gridLayout.addWidget(self.lblLayer, 8, 0, 1, 1)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.label_3 = QtGui.QLabel(self.gbTileCacheSettings)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self._2.addWidget(self.label_3)
        self.spnXmax = QtGui.QDoubleSpinBox(self.gbTileCacheSettings)
        self.spnXmax.setMinimum(-1000000000.0)
        self.spnXmax.setMaximum(1000000000.0)
        self.spnXmax.setObjectName(_fromUtf8("spnXmax"))
        self._2.addWidget(self.spnXmax)
        self.gridLayout.addLayout(self._2, 24, 0, 1, 1)
        self.lblExtents = QtGui.QLabel(self.gbTileCacheSettings)
        self.lblExtents.setObjectName(_fromUtf8("lblExtents"))
        self.gridLayout.addWidget(self.lblExtents, 21, 0, 1, 1)
        self._3 = QtGui.QHBoxLayout()
        self._3.setObjectName(_fromUtf8("_3"))
        self.label_4 = QtGui.QLabel(self.gbTileCacheSettings)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self._3.addWidget(self.label_4)
        self.spnYmin = QtGui.QDoubleSpinBox(self.gbTileCacheSettings)
        self.spnYmin.setMinimum(-1000000000.0)
        self.spnYmin.setMaximum(1000000000.0)
        self.spnYmin.setObjectName(_fromUtf8("spnYmin"))
        self._3.addWidget(self.spnYmin)
        spacerItem = QtGui.QSpacerItem(230, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._3.addItem(spacerItem)
        self.gridLayout.addLayout(self._3, 23, 1, 1, 1)
        self.tbGetLayers = QtGui.QToolButton(self.gbTileCacheSettings)
        self.tbGetLayers.setObjectName(_fromUtf8("tbGetLayers"))
        self.gridLayout.addWidget(self.tbGetLayers, 8, 2, 1, 1)
        self.leLayer = QtGui.QLineEdit(self.gbTileCacheSettings)
        self.leLayer.setObjectName(_fromUtf8("leLayer"))
        self.gridLayout.addWidget(self.leLayer, 8, 1, 1, 1)
        self.spMaxZoom = QtGui.QSpinBox(self.gbTileCacheSettings)
        self.spMaxZoom.setMinimum(1)
        self.spMaxZoom.setMaximum(21)
        self.spMaxZoom.setObjectName(_fromUtf8("spMaxZoom"))
        self.gridLayout.addWidget(self.spMaxZoom, 11, 1, 1, 1)
        self.cmbExtents = QtGui.QComboBox(self.gbTileCacheSettings)
        self.cmbExtents.setObjectName(_fromUtf8("cmbExtents"))
        self.gridLayout.addWidget(self.cmbExtents, 21, 1, 1, 1)
        self.tbCacheDir = QtGui.QToolButton(self.gbTileCacheSettings)
        self.tbCacheDir.setObjectName(_fromUtf8("tbCacheDir"))
        self.gridLayout.addWidget(self.tbCacheDir, 1, 2, 1, 1)
        self.lblMaxZoom = QtGui.QLabel(self.gbTileCacheSettings)
        self.lblMaxZoom.setObjectName(_fromUtf8("lblMaxZoom"))
        self.gridLayout.addWidget(self.lblMaxZoom, 11, 0, 1, 1)
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName(_fromUtf8("_4"))
        self.label_5 = QtGui.QLabel(self.gbTileCacheSettings)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self._4.addWidget(self.label_5)
        self.spnYmax = QtGui.QDoubleSpinBox(self.gbTileCacheSettings)
        self.spnYmax.setMinimum(-1000000000.0)
        self.spnYmax.setMaximum(1000000000.0)
        self.spnYmax.setObjectName(_fromUtf8("spnYmax"))
        self._4.addWidget(self.spnYmax)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._4.addItem(spacerItem1)
        self.gridLayout.addLayout(self._4, 24, 1, 1, 1)
        self.btnCanvas = QtGui.QToolButton(self.gbTileCacheSettings)
        self.btnCanvas.setMinimumSize(QtCore.QSize(0, 30))
        self.btnCanvas.setObjectName(_fromUtf8("btnCanvas"))
        self.gridLayout.addWidget(self.btnCanvas, 22, 1, 1, 1)
        self.lblSourceName = QtGui.QLabel(self.gbTileCacheSettings)
        self.lblSourceName.setObjectName(_fromUtf8("lblSourceName"))
        self.gridLayout.addWidget(self.lblSourceName, 2, 0, 1, 1)
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName(_fromUtf8("_5"))
        self.label = QtGui.QLabel(self.gbTileCacheSettings)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self._5.addWidget(self.label)
        self.spnXmin = QtGui.QDoubleSpinBox(self.gbTileCacheSettings)
        self.spnXmin.setMinimum(-1000000000.0)
        self.spnXmin.setMaximum(1000000000.0)
        self.spnXmin.setObjectName(_fromUtf8("spnXmin"))
        self._5.addWidget(self.spnXmin)
        self.gridLayout.addLayout(self._5, 23, 0, 1, 1)
        self.leTileCacheDir = QtGui.QLineEdit(self.gbTileCacheSettings)
        self.leTileCacheDir.setObjectName(_fromUtf8("leTileCacheDir"))
        self.gridLayout.addWidget(self.leTileCacheDir, 1, 1, 1, 1)
        self.leURL = QtGui.QLineEdit(self.gbTileCacheSettings)
        self.leURL.setObjectName(_fromUtf8("leURL"))
        self.gridLayout.addWidget(self.leURL, 4, 1, 1, 1)
        self.lblType = QtGui.QLabel(self.gbTileCacheSettings)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 9, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rdoWMS = QtGui.QRadioButton(self.gbTileCacheSettings)
        self.rdoWMS.setEnabled(False)
        self.rdoWMS.setChecked(True)
        self.rdoWMS.setObjectName(_fromUtf8("rdoWMS"))
        self.horizontalLayout.addWidget(self.rdoWMS)
        self.rdoNotValid = QtGui.QRadioButton(self.gbTileCacheSettings)
        self.rdoNotValid.setEnabled(False)
        self.rdoNotValid.setObjectName(_fromUtf8("rdoNotValid"))
        self.horizontalLayout.addWidget(self.rdoNotValid)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbTileCacheSettings)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblFormat = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblFormat.setObjectName(_fromUtf8("lblFormat"))
        self.horizontalLayout_4.addWidget(self.lblFormat)
        self.rdoJPG = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoJPG.setChecked(True)
        self.rdoJPG.setObjectName(_fromUtf8("rdoJPG"))
        self.horizontalLayout_4.addWidget(self.rdoJPG)
        self.rdoPNG = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoPNG.setObjectName(_fromUtf8("rdoPNG"))
        self.horizontalLayout_4.addWidget(self.rdoPNG)
        self.rdoGIF = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoGIF.setObjectName(_fromUtf8("rdoGIF"))
        self.horizontalLayout_4.addWidget(self.rdoGIF)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.pbZoomProgress = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.pbZoomProgress.setProperty("value", 0)
        self.pbZoomProgress.setObjectName(_fromUtf8("pbZoomProgress"))
        self.verticalLayout.addWidget(self.pbZoomProgress)
        self.pbTileProgress = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.pbTileProgress.setProperty("value", 0)
        self.pbTileProgress.setObjectName(_fromUtf8("pbTileProgress"))
        self.verticalLayout.addWidget(self.pbTileProgress)
        self.line_4 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbBuild = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbBuild.setEnabled(False)
        self.pbBuild.setObjectName(_fromUtf8("pbBuild"))
        self.horizontalLayout_2.addWidget(self.pbBuild)
        self.pbSaveConfig = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbSaveConfig.setEnabled(False)
        self.pbSaveConfig.setObjectName(_fromUtf8("pbSaveConfig"))
        self.horizontalLayout_2.addWidget(self.pbSaveConfig)
        self.pbCancel = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbCancel.setEnabled(False)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.horizontalLayout_2.addWidget(self.pbCancel)
        self.pbClose = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.horizontalLayout_2.addWidget(self.pbClose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(TileCacheCreator)
        QtCore.QObject.connect(self.pbClose, QtCore.SIGNAL(_fromUtf8("clicked()")), TileCacheCreator.reject)
        QtCore.QMetaObject.connectSlotsByName(TileCacheCreator)
        TileCacheCreator.setTabOrder(self.leTileCacheConfig, self.tbConfigFile)
        TileCacheCreator.setTabOrder(self.tbConfigFile, self.leTileCacheDir)
        TileCacheCreator.setTabOrder(self.leTileCacheDir, self.leSourceName)
        TileCacheCreator.setTabOrder(self.leSourceName, self.leURL)
        TileCacheCreator.setTabOrder(self.leURL, self.leLayer)
        TileCacheCreator.setTabOrder(self.leLayer, self.tbCacheDir)
        TileCacheCreator.setTabOrder(self.tbCacheDir, self.tbGetLayers)
        TileCacheCreator.setTabOrder(self.tbGetLayers, self.rdoWMS)
        TileCacheCreator.setTabOrder(self.rdoWMS, self.rdoNotValid)
        TileCacheCreator.setTabOrder(self.rdoNotValid, self.spMinZoom)
        TileCacheCreator.setTabOrder(self.spMinZoom, self.spMaxZoom)
        TileCacheCreator.setTabOrder(self.spMaxZoom, self.cmbExtents)
        TileCacheCreator.setTabOrder(self.cmbExtents, self.btnUpdate)
        TileCacheCreator.setTabOrder(self.btnUpdate, self.btnCanvas)
        TileCacheCreator.setTabOrder(self.btnCanvas, self.spnXmin)
        TileCacheCreator.setTabOrder(self.spnXmin, self.spnXmax)
        TileCacheCreator.setTabOrder(self.spnXmax, self.spnYmin)
        TileCacheCreator.setTabOrder(self.spnYmin, self.spnYmax)
        TileCacheCreator.setTabOrder(self.spnYmax, self.pbBuild)
        TileCacheCreator.setTabOrder(self.pbBuild, self.pbSaveConfig)
        TileCacheCreator.setTabOrder(self.pbSaveConfig, self.pbClose)
        TileCacheCreator.setTabOrder(self.pbClose, self.rdoJPG)
        TileCacheCreator.setTabOrder(self.rdoJPG, self.rdoPNG)
        TileCacheCreator.setTabOrder(self.rdoPNG, self.rdoGIF)
        TileCacheCreator.setTabOrder(self.rdoGIF, self.pbCancel)

    def retranslateUi(self, TileCacheCreator):
        TileCacheCreator.setWindowTitle(QtGui.QApplication.translate("TileCacheCreator", "TileCache Creator Version 0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCacheName.setText(QtGui.QApplication.translate("TileCacheCreator", "TileCache Configuration File:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbConfigFile.setToolTip(QtGui.QApplication.translate("TileCacheCreator", "Select Configuration File", None, QtGui.QApplication.UnicodeUTF8))
        self.tbConfigFile.setText(QtGui.QApplication.translate("TileCacheCreator", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTileCacheSettings.setTitle(QtGui.QApplication.translate("TileCacheCreator", "TileCache Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TileCacheCreator", "TileCache Dir Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("TileCacheCreator", "Update extents from layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMinZoom.setText(QtGui.QApplication.translate("TileCacheCreator", "Minimum Zoom:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblURL.setText(QtGui.QApplication.translate("TileCacheCreator", "Source URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayer.setText(QtGui.QApplication.translate("TileCacheCreator", "Service Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TileCacheCreator", "X Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblExtents.setText(QtGui.QApplication.translate("TileCacheCreator", "Project Extents Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TileCacheCreator", "Y Min: ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGetLayers.setToolTip(QtGui.QApplication.translate("TileCacheCreator", "Verify Service & Select Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGetLayers.setText(QtGui.QApplication.translate("TileCacheCreator", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCacheDir.setToolTip(QtGui.QApplication.translate("TileCacheCreator", "Select TileCache Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCacheDir.setText(QtGui.QApplication.translate("TileCacheCreator", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaxZoom.setText(QtGui.QApplication.translate("TileCacheCreator", "Maximum Zoom:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TileCacheCreator", "Y Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCanvas.setText(QtGui.QApplication.translate("TileCacheCreator", "Update extents from canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSourceName.setText(QtGui.QApplication.translate("TileCacheCreator", "Source Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TileCacheCreator", "X Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblType.setText(QtGui.QApplication.translate("TileCacheCreator", "Service Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoWMS.setText(QtGui.QApplication.translate("TileCacheCreator", "WMS", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoNotValid.setText(QtGui.QApplication.translate("TileCacheCreator", "Not Valid", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFormat.setText(QtGui.QApplication.translate("TileCacheCreator", "Tile Image Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoJPG.setText(QtGui.QApplication.translate("TileCacheCreator", "JPG", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoPNG.setText(QtGui.QApplication.translate("TileCacheCreator", "PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoGIF.setText(QtGui.QApplication.translate("TileCacheCreator", "GIF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TileCacheCreator", "Disk TileCache Projection:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TileCacheCreator", "EPSG: 3857", None, QtGui.QApplication.UnicodeUTF8))
        self.pbZoomProgress.setFormat(QtGui.QApplication.translate("TileCacheCreator", "Zoom Levels %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTileProgress.setFormat(QtGui.QApplication.translate("TileCacheCreator", "Tiles %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.pbBuild.setText(QtGui.QApplication.translate("TileCacheCreator", "Create / Update", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveConfig.setText(QtGui.QApplication.translate("TileCacheCreator", "Save Config File", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("TileCacheCreator", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("TileCacheCreator", "Close", None, QtGui.QApplication.UnicodeUTF8))

